#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config external_bar all:40:0 \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_topmost off \
    window_shadow float \
    window_opacity on \
    window_opacity_duration 0.15 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.95 \
    window_animation_duration 0.22 \
    insert_feedback_color 0xff9dd274 \
    split_ratio 0.50 \
    auto_balance off \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    top_padding 10 \
    bottom_padding 10 \
    left_padding 10 \
    right_padding 10 \
    window_gap 8

# Exclude problematic apps from being managed
yabai -m rule --add app="MGJavaClientMain" manage=off
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Firefox" app="^Firefox$" title="^(General|Home|Search|Library|Extension|Privacy|Security|Extensions|Downloads|Applications|Fonts|Colors|Languages|Network|Certificates|Advanced)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Firefox Bitwarden" app="^Firefox$" title="^Extension: \(Bitwarden Password Manager\) -.*$" manage=off
# IntelliJ
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA)$'
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on space=2
yabai -m rule --add app="${JB_Apps}" title="^$" manage=on space=2

yabai -m config layout bsp

echo "yabai configuration loaded.."
