#!/bin/bash

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
NERD_FONT="Liga SFMono Nerd Font"
export PADDINGS=3 # All paddings use this value (icon, label, background)

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"            # Directory where the items are configured
export PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar_config=(
	blur_radius=30
	color=0
	border_color=$BAR_BORDER_COLOR
	corner_radius=9
	height=45
	margin=10
	padding_left=10
	padding_right=10
	position=top
	shadow=on
	sticky=on
	topmost=off
	y_offset=0
	margin=0
)
icon_defaults=(
	icon.color="$ICON_COLOR"
	icon.font="$NERD_FONT:Bold:16.0"
	icon.padding_left=10
	icon.padding_right=10
)

label_defaults=(
	label.color=$LABEL_COLOR
	label.font="$FONT:Bold:10.0"
	label.padding_left=5
	label.padding_right=5
)
background_defaults=(
	background.height=30
	background.corner_radius=8
	background.border_width=2
	background.padding_left=5
	background.padding_right=5
)



popup_defaults=(
	popup.height=30
	popup.horizontal=false
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.border_width=2
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.background.corner_radius=11
	popup.background.shadow.drawing=on
)

sketchybar --bar "${bar_config[@]}" \
	--default \
	updates=when_shown \
	"${icon_defaults[@]}" \
	"${label_defaults[@]}" \
	"${background_defaults[@]}" \
	"${popup_defaults[@]}"

# Setting up default valu

# Left
source "$PLUGIN_DIR/apple/item.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$PLUGIN_DIR/locale/item.sh"
source "$PLUGIN_DIR/time/item.sh"
source "$PLUGIN_DIR/spacers/spacer.sh"
source "$PLUGIN_DIR/date/item.sh"
source "$PLUGIN_DIR/spacers/spacer2.sh"
source "$PLUGIN_DIR/battery/item.sh"
source "$PLUGIN_DIR/wifi/item.sh"
#source "$PLUGIN_DIR/github/item.sh"
source "$PLUGIN_DIR/stats/item.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
